CWD=.
SIGNATURE=1588417722,13496
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal  -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -DSHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_EXTRACT hsegextract.cc -o hsegextract.o
IMPLICIT_TARGETS=hsegextract.o
SIG_METHOD_IMPLICIT=1
META_DEPS=/usr/bin/g++hsegextract.ccsys../defines.h../point/point.h../shape/shape.hclimitscstdlibcstringdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/region_class.hparallel/region_object.hparams/params.hregion/region_class.hregion/region_object.hresults/results.hsetspatial/spatial.hsstreamstdexceptstringvectoruser./hsegextract.hparams/initialParams.h
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009rbwxftWKl6FUS+1PV7cuTwQBVlvoyFuHDP2vYtxUAruQCm5XOfDRYWcPtlBkU8K9DwnrcVU0l3iFCSIhsCbDoVFwiDuneRwt2XcpOLXZYEHjZAbHzduVfmpQZiPcjKFstUvAuqVJLOXFsS3kiHM31G/1/gQkhYfQY2ZFHF5fjcjUcquQU0zUr4GDuuZM4IbkmJwifAcHtwjdkjFzwbxwGCtTJaBgxlpppl+HgYGYCorfrhAbDg
BUILD_SIGNATURE=1588417722,13496
ARCH=x86_64-linux-gnu-thread-multi
INCLUDE_SFXS=
SORTED_DEPS=../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.hhsegextract.cchsegextract.h/home/pswang/src/CommonV1.70/image/image.hparams/initialParams.h../../params/params.h../../results/results.h../../spatial/spatial.h../../parallel/region_class.h../../parallel/region_object.h../../region/region_class.h../../region/region_object.h
END=