ARCH=x86_64-linux-gnu-thread-multi
SIGNATURE=1588417795,13840
CWD=.
INCLUDE_SFXS=
SORTED_DEPS=../../spatial/boundary_map.cc../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h../../spatial/spatial.h../../index/index.h../../parallel/hseg.h../../parallel/index.h../../parallel/pixel.h../../pixel/pixel.h../../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../spatial/boundary_map.cc -o boundary_map.o
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417795,13840
SIG_METHOD_IMPLICIT=1
IMPLICIT_DEPS=
IMPLICIT_TARGETS=boundary_map.o
META_DEPS=../../spatial/boundary_map.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibcstringctimedefines.hfstreamgdal_priv.hgdalwarper.himage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparams/params.hpixel/pixel.hrhseg/hseg.hsetsstreamstdexceptstringvectoruser../../spatial/spatial.h
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
DEP_SIGS=sOjasVvrSiDDX5HlP7Cbvgz/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7Cgp8ynGaUtUItYTP9WYpFtZAvm03ZpR0EzimwuTG4WA6Zg
END=