INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
META_DEPS=../../spatial/find_section.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammpi.hparams/params.hsstreamstdexceptstringvector
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQhmxuI+DdhtvgDj4w0j0W7g1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZA
IMPLICIT_TARGETS=find_section.o
IMPLICIT_DEPS=
SIG_METHOD_IMPLICIT=1
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../spatial/find_section.cc -o find_section.o
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417800,2880
SORTED_DEPS=../../defines.h../../spatial/find_section.cc/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h
INCLUDE_SFXS=
CWD=.
SIGNATURE=1588417800,2880
ARCH=x86_64-linux-gnu-thread-multi
END=