ARCH=x86_64-linux-gnu-thread-multi
CWD=.
SIGNATURE=1588417799,4136
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/find_nghbr.cc -o find_nghbr.o
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417799,4136
SIG_METHOD_IMPLICIT=1
INCLUDE_SFXS=
SORTED_DEPS=../defines.h../rhseg/find_nghbr.cc/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../params/params.h
IMPLICIT_TARGETS=find_nghbr.o
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQODz2dE6LG1kRuvw8h0scww1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZA
META_DEPS=../rhseg/find_nghbr.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammpi.hparams/params.hsstreamstdexceptstringvector
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
IMPLICIT_DEPS=
END=