BUILD_SIGNATURE=1574278509,12848
ARCH=x86_64-linux-thread-multi
META_DEPS=../rhseg/artifact_elimination.cc/usr/bin/g++sys../defines.hclimitscstdlibdefines.hfloat.hfstreamimage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparallel/region_class.hparams/params.hpixel/pixel.hregion/region_class.hregion/region_seam.hrhseg/hseg.hsetsstreamstdexceptstringvectoruser../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/artifact_elimination.cc -o artifact_elimination.o
SORTED_DEPS=../rhseg/artifact_elimination.cc../defines.h/usr/bin/g++../params/params.h../region/region_seam.h../index/index.h../parallel/hseg.h../parallel/index.h../parallel/pixel.h../parallel/region_class.h../pixel/pixel.h../region/region_class.h../rhseg/hseg.h
IMPLICIT_TARGETS=artifact_elimination.o
CWD=.
INCLUDE_SFXS=
SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278509,12848
DEP_SIGS=sZ/ysT+KoaIAfwq++J6gGAz/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAha3YNAtMdZOmbsqt3mDcfgWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
END=