IMPLICIT_TARGETS=find_nghbr.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/find_nghbr.cc -o find_nghbr.o
SORTED_DEPS=../defines.h../rhseg/find_nghbr.cc/usr/bin/g++../params/params.h
INCLUDE_SFXS=
CWD=.
BUILD_SIGNATURE=1574278512,4528
ARCH=x86_64-linux-thread-multi
META_DEPS=../rhseg/find_nghbr.cc/usr/bin/g++sysclimitscstdlibdefines.hfstreamimage/image.hmpi.hparams/params.hsstreamstdexceptstringvector
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278512,4528
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQODz2dE6LG1kRuvw8h0scww1566927917,1226608iDuneRwt2XcpOLXZYEHjZA
SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
END=