SIG_METHOD_NAME=C
SIG_METHOD_IMPLICIT=1
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,12266089imYklOwtG68GzkJvaSsvAiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278519,55728
BUILD_SIGNATURE=1574278519,55728
ARCH=x86_64-linux-thread-multi
META_DEPS=../rhseg/lrhseg.cc/usr/bin/g++sys../defines.halgorithmclimitscstdlibcstringctimedefines.hfloat.hfstreamimage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparallel/region_class.hparams/params.hpixel/pixel.hregion/region_class.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../rhseg/hseg.h
CWD=.
INCLUDE_SFXS=
SORTED_DEPS=../defines.h/usr/bin/g++../rhseg/lrhseg.cc../params/params.h../spatial/spatial.h../index/index.h../parallel/hseg.h../parallel/index.h../parallel/pixel.h../parallel/region_class.h../pixel/pixel.h../region/region_class.h../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/lrhseg.cc -o lrhseg.o
IMPLICIT_TARGETS=lrhseg.o
END=