SIG_METHOD_NAME=C
INCLUDE_SFXS=
IMPLICIT_DEPS=
COMMAND=g++ -c -Wall -O3 -ffloat-store -I/home/pswang/src/CommonV1.70 -Wno-unused-result -I/usr/include/gdal  -DGDAL -DSHAPEFILE shape_info.cc -o shape_info.o
DEP_SIGS=1586428689,1158288Cy8fU09+orabSSF5viHvxwC3ImBrbFzFqSuOt8pZ730Q/TtsDo9cGFOjahoMprh5zw9nft+jPkokocfIla5sCwBAIjH8/OH3fCxzICcrfsCZow1584892663,27327
META_DEPS=/usr/bin/g++shape_info.ccsysiostreamlistshape/shape.hshapefil.hstringvectoruser./params/params.hshape_info.h/home/pswang/src/CommonV1.70/shape/../point/point.h
ARCH=x86_64-linux-gnu-thread-multi
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/usr/include/gdal/usr/includeuserin CPATHin :sys
SIGNATURE=1601514726,4736
IMPLICIT_TARGETS=shape_info.o
BUILD_SIGNATURE=1601514726,4736
SIG_METHOD_IMPLICIT=1
SORTED_DEPS=/usr/bin/g++params/params.h/home/pswang/src/CommonV1.70/point/point.h/home/pswang/src/CommonV1.70/shape/shape.hshape_info.ccshape_info.h/usr/include/shapefil.h
CWD=.
END=