SIG_METHOD_IMPLICIT=1
IMPLICIT_TARGETS=friends.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN ../../params/friends.cc -o friends.o
SIGNATURE=1588417692,3816
CWD=.
SORTED_DEPS=../../defines.h../../params/friends.cc/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h
INCLUDE_SFXS=
ARCH=x86_64-linux-gnu-thread-multi
BUILD_SIGNATURE=1588417692,3816
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQkk431R0kod0wHLsKTWOgGA1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZA
IMPLICIT_DEPS=
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
SIG_METHOD_NAME=C
META_DEPS=../../params/friends.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammpi.hsstreamstdexceptstringvectoruser../../params/params.h
END=