SIG_METHOD_NAME=C
SIG_METHOD_IMPLICIT=1
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAuw6c7QSkflXCPkWeqgOy0AuqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQU0zUr4GDuuZM4IbkmJwifAp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgxlpppl+HgYGYCorfrhAbDgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
SIGNATURE=1574278529,94592
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
META_DEPS=../../spatial/spatial.cc/usr/bin/g++sys../defines.hclimitscstdlibcstringctimedefines.hfloat.hfstreamimage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparallel/region_class.hparallel/region_object.hparams/params.hpixel/pixel.hregion/region_class.hregion/region_object.hrhseg/hseg.hsetsstreamstdexceptstringvectoruser../../spatial/spatial.h
ARCH=x86_64-linux-thread-multi
BUILD_SIGNATURE=1574278529,94592
CWD=.
INCLUDE_SFXS=
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../spatial/spatial.cc -o spatial.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../params/params.h../../spatial/spatial.cc../../spatial/spatial.h../../index/index.h../../parallel/hseg.h../../parallel/index.h../../parallel/pixel.h../../parallel/region_class.h../../parallel/region_object.h../../pixel/pixel.h../../region/region_class.h../../region/region_object.h../../rhseg/hseg.h
IMPLICIT_TARGETS=spatial.o
END=