ARCH=x86_64-linux-gnu-thread-multi
SIGNATURE=1588417832,3816
CWD=.
INCLUDE_SFXS=
SORTED_DEPS=../../defines.h../../params/friends.cc/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h
BUILD_SIGNATURE=1588417832,3816
SIG_METHOD_NAME=C
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_SETUP ../../params/friends.cc -o friends.o
SIG_METHOD_IMPLICIT=1
IMPLICIT_DEPS=
IMPLICIT_TARGETS=friends.o
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQkk431R0kod0wHLsKTWOgGA1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZA
META_DEPS=../../params/friends.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammpi.hsstreamstdexceptstringvectoruser../../params/params.h
END=