CWD=.
SIG_METHOD_IMPLICIT=1
IMPLICIT_TARGETS=update_region_label.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN ../../spatial/update_region_label.cc -o update_region_label.o
SIGNATURE=1588417720,3792
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
META_DEPS=../../spatial/update_region_label.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibcstringctimedefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparallel/pixel.hparams/params.hpixel/pixel.hrhseg/hseg.hsetsstreamstdexceptstringvectoruser../../spatial/spatial.h
SIG_METHOD_NAME=C
INCLUDE_SFXS=
SORTED_DEPS=../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h../../spatial/spatial.h../../spatial/update_region_label.cc../../parallel/hseg.h../../parallel/pixel.h../../pixel/pixel.h../hseg.h
ARCH=x86_64-linux-gnu-thread-multi
BUILD_SIGNATURE=1588417720,3792
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gwtu3tLDgyRGoPzPPHgC8fAgjuOGgPKZisdJk8h4wLvqAH6t/l0ZBFX4I/UBMIG/7Cgp8ynGaUtUItYTP9WYpFtZAvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
END=