SIG_METHOD_NAME=C
META_DEPS=/usr/bin/g++main.ccsys../point/point.h../shape/shape.hclimitscstdlibcstringdefines.hfstreamgdal_priv.hgdalwarper.hgtkmm.hgui/fileObject.hgui/numberObject.himage/image.hiostreammpi.hparams/params.hsstreamstdexceptstringvectoruser./hsegextract.hparams/initialParams.hparams/paramsGUI.h
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
BUILD_SIGNATURE=1588417728,18448
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQce1LpOPQ2i8GUOqymaDn9g1586428689,11582881585509601,723681585509601,24009QBVlvoyFuHDP2vYtxUAruQCm5XOfDRYWcPtlBkU8K9DwnrcVU0l3iFCSIhsCbDoVFwWnMpJBD/boNhsdKcJrF5BgzJOedzGRSkZBUFKXmYLZXAiDuneRwt2XcpOLXZYEHjZAN6cTk+xsvE7T2YaYfDHNPQ
IMPLICIT_DEPS=
SORTED_DEPS=../../defines.h/home/pswang/src/CommonV1.70/gui/fileObject.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.hhsegextract.h/home/pswang/src/CommonV1.70/image/image.hparams/initialParams.hmain.cc/home/pswang/src/CommonV1.70/gui/numberObject.h../../params/params.hparams/paramsGUI.h
INCLUDE_SFXS=
ARCH=x86_64-linux-gnu-thread-multi
CWD=.
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal  -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -DSHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_EXTRACT main.cc -o main.o
SIGNATURE=1588417728,18448
SIG_METHOD_IMPLICIT=1
IMPLICIT_TARGETS=main.o
END=