SIG_METHOD_IMPLICIT=1
IMPLICIT_TARGETS=region_object.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN ../../region/region_object.cc -o region_object.o
SIGNATURE=1588417713,89240
CWD=.
INCLUDE_SFXS=
SORTED_DEPS=../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h../../spatial/spatial.h../../parallel/hseg.h../../parallel/pixel.h../../parallel/region_class.h../../parallel/region_object.cc../../parallel/region_object.h../../pixel/pixel.h../../region/region_class.h../../region/region_object.cc../../region/region_object.h../hseg.h
ARCH=x86_64-linux-gnu-thread-multi
BUILD_SIGNATURE=1588417713,89240
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/ggjuOGgPKZisdJk8h4wLvqAH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQ2GyqQujPwNLJwakQ0yjVmwU0zUr4GDuuZM4IbkmJwifAp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgzmdHk9xRrBHI0Qjmt+9msgxlpppl+HgYGYCorfrhAbDgvm03ZpR0EzimwuTG4WA6Zg
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
META_DEPS=../../region/region_object.cc/usr/bin/g++sys../defines.h../point/point.h../shape/shape.hclimitscmathcstdlibcstringdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparallel/pixel.hparallel/region_class.hparallel/region_object.ccparallel/region_object.hparams/params.hpixel/pixel.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../region/region_class.hregion_object.h
SIG_METHOD_NAME=C
END=