IMPLICIT_TARGETS=friends.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../params/friends.cc -o friends.o
SORTED_DEPS=../../defines.h../../params/friends.cc/usr/bin/g++../../params/params.h
CWD=.
INCLUDE_SFXS=
META_DEPS=../../params/friends.cc/usr/bin/g++sysclimitscstdlibdefines.hfstreamimage/image.hmpi.hsstreamstdexceptstringvectoruser../../params/params.h
ARCH=x86_64-linux-thread-multi
BUILD_SIGNATURE=1574278513,2904
SIGNATURE=1574278513,2904
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQkk431R0kod0wHLsKTWOgGA1566927917,1226608iDuneRwt2XcpOLXZYEHjZA
SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
END=