SIG_METHOD_IMPLICIT=1
CWD=.
SORTED_DEPS=/usr/bin/g++main.ccparams/params.h/home/pswang/src/CommonV1.70/point/point.h/home/pswang/src/CommonV1.70/shape/shape.hshape_info.h/usr/include/shapefil.h
BUILD_SIGNATURE=1601514724,14864
IMPLICIT_TARGETS=main.o
DEP_SIGS=1586428689,1158288vBbkvsoow1ng4rRRZJqqAACy8fU09+orabSSF5viHvxwC3ImBrbFzFqSuOt8pZ730Q/TtsDo9cGFOjahoMprh5zwIjH8/OH3fCxzICcrfsCZow1584892663,27327
META_DEPS=/usr/bin/g++main.ccsyscstdlibcstringfstreamiostreamlistshape/shape.hshapefil.hstringvectoruser./params/params.hshape_info.h/home/pswang/src/CommonV1.70/shape/../point/point.h
ARCH=x86_64-linux-gnu-thread-multi
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/usr/include/gdal/usr/includeuserin CPATHin :sys
SIGNATURE=1601514724,14864
SIG_METHOD_NAME=C
INCLUDE_SFXS=
IMPLICIT_DEPS=
COMMAND=g++ -c -Wall -O3 -ffloat-store -I/home/pswang/src/CommonV1.70 -Wno-unused-result -I/usr/include/gdal  -DGDAL -DSHAPEFILE main.cc -o main.o
END=