SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278515,34688
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608ccDTMY7YP2RESg5xxovrNAiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7Cgp8ynGaUtUItYTP9WYpFtZAvm03ZpR0EzimwuTG4WA6Zg
BUILD_SIGNATURE=1574278515,34688
ARCH=x86_64-linux-thread-multi
META_DEPS=../../index/get_seam_index_data.cc/usr/bin/g++sysclimitscstdlibcstringctimedefines.hfstreamimage/image.hmapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparams/params.hpixel/pixel.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../index/index.h
IMPLICIT_TARGETS=get_seam_index_data.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../index/get_seam_index_data.cc -o get_seam_index_data.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../index/get_seam_index_data.cc../../params/params.h../../spatial/spatial.h../../index/index.h../../parallel/hseg.h../../parallel/index.h../../parallel/pixel.h../../pixel/pixel.h../../rhseg/hseg.h
CWD=.
INCLUDE_SFXS=
END=