BUILD_SIGNATURE=1574278514,34416
ARCH=x86_64-linux-thread-multi
META_DEPS=../../index/get_border_index_data.cc/usr/bin/g++sysclimitscstdlibcstringctimedefines.hfstreamimage/image.hmapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparams/params.hpixel/pixel.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../index/index.h
CWD=.
INCLUDE_SFXS=
IMPLICIT_TARGETS=get_border_index_data.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../index/get_border_index_data.cc../../params/params.h../../spatial/spatial.h../../index/index.h../../parallel/hseg.h../../parallel/index.h../../parallel/pixel.h../../pixel/pixel.h../../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../index/get_border_index_data.cc -o get_border_index_data.o
SIG_METHOD_NAME=C
SIG_METHOD_IMPLICIT=1
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,12266083JcKXbVygg4HaLmQ/Ur0gQiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7Cgp8ynGaUtUItYTP9WYpFtZAvm03ZpR0EzimwuTG4WA6Zg
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278514,34416
END=