SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278517,7672
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/g0KEJaT4HrHhcTew/tP9OvwWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqA/4wawWsKlfS4kSaw21t50gubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
BUILD_SIGNATURE=1574278517,7672
ARCH=x86_64-linux-thread-multi
META_DEPS=../../index/index.cc/usr/bin/g++sys../defines.hclimitscstdlibcstringdefines.hfloat.hfstreamimage/image.hmapmpi.hparallel/hseg.hparallel/index.ccparallel/index.hparallel/pixel.hparallel/region_class.hparams/params.hpixel/pixel.hregion/region_class.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../index/index.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../index/index.cc -o index.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../params/params.h../../spatial/spatial.h../../index/index.cc../../index/index.h../../parallel/hseg.h../../parallel/index.cc../../parallel/index.h../../parallel/pixel.h../../parallel/region_class.h../../pixel/pixel.h../../region/region_class.h../../rhseg/hseg.h
IMPLICIT_TARGETS=index.o
CWD=.
INCLUDE_SFXS=
END=