SIGNATURE=1534445019,30208
SIG_METHOD_IMPLICIT=1
DEP_SIGS=1516653975,44763z/QeDlmwxoI4L/bLCeMkSQce1LpOPQ2i8GUOqymaDn9g1523291714,7727441516653976,628201516653976,22263IaTZM6pejxn6nbNg6k5SVA0wanbfcnNkakvhmdf5v1qgjswVGE1VKQ7Dg86dFmu6GQ4qTCXXSbbllLkrb0vP3qYQzJOedzGRSkZBUFKXmYLZXAqj8Ivpinlk0EkcICCAFghgiDuneRwt2XcpOLXZYEHjZAFqUobXjx+i8JSyW4D0szcQ
SORTED_DEPS=/apps/gdal/2.2.3/include/cpl_port.h../defines.h/gpfs/glad1/Panshi/src/CommonV1.70/gui/fileObject.h/usr/bin/g++/apps/gdal/2.2.3/include/gdal_priv.h/apps/gdal/2.2.3/include/gdalwarper.h/gpfs/glad1/Panshi/src/CommonV1.70/image/image.h../params/initialGUI.h../rhseg_setup/main.cc/gpfs/glad1/Panshi/src/CommonV1.70/gui/numberListObject.h/gpfs/glad1/Panshi/src/CommonV1.70/gui/numberObject.h../params/outputFileGUI.h../params/params.h../params/paramsGUI.h
INCLUDE_SFXS=
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/wangp/wk/src/CommonV1.70 -I/home/wangp/wk/src/RHSEG/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_SETUP ../rhseg_setup/main.cc -o main.o
BUILD_SIGNATURE=1534445019,30208
IMPLICIT_TARGETS=main.o
META_DEPS=../rhseg_setup/main.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscpl_port.hcstdlibcstringdefines.hexpParamsGUI.hfstreamgdal_priv.hgdalwarper.hgtkmm.hgui/fileObject.hgui/numberListObject.hgui/numberObject.himage/image.hiostreammpi.hparams/initialGUI.hparams/outputFileGUI.hparams/params.hparams/paramsGUI.hsstreamstdexceptstringvector
ARCH=x86_64-linux
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/wangp/wk/src/CommonV1.70/home/wangp/wk/src/RHSEG/rhsegV1.61/usr/includeuserin CPATHin :sys
CWD=.
IMPLICIT_DEPS=
SIG_METHOD_NAME=C
END=