CWD=.
SIGNATURE=1588417785,74792
ARCH=x86_64-linux-gnu-thread-multi
IMPLICIT_TARGETS=initialParams.o
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
META_DEPS=/usr/bin/g++initialParams.ccsys../point/point.h../shape/shape.hclimitscstdlibdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammpi.hparams/params.hsstreamstdexceptstringvectoruser./initialParams.h
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwqDsEmi7dh+KBLwQJEZqnPAt2tyxL1aCgkHuZnq3JoOYgiDuneRwt2XcpOLXZYEHjZA
IMPLICIT_DEPS=
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_READ initialParams.cc -o initialParams.o
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417785,74792
SIG_METHOD_IMPLICIT=1
INCLUDE_SFXS=
SORTED_DEPS=../../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.hinitialParams.ccinitialParams.h../../../params/params.h
END=