IMPLICIT_TARGETS=trace_region_boundary.o
SIG_METHOD_IMPLICIT=1
SIGNATURE=1588417737,22496
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal  -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -DSHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_EXTRACT ../../../spatial/trace_region_boundary.cc -o trace_region_boundary.o
CWD=.
ARCH=x86_64-linux-gnu-thread-multi
INCLUDE_SFXS=
SORTED_DEPS=../../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../../params/params.h../../../spatial/spatial.h../../../spatial/trace_region_boundary.cc
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gQVRw9ny2Kv2f+q+uQdrgvg
IMPLICIT_DEPS=
BUILD_SIGNATURE=1588417737,22496
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
META_DEPS=../../../spatial/trace_region_boundary.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibcstringdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparams/params.hsetsstreamstdexceptstringvectoruser../../../spatial/spatial.h
SIG_METHOD_NAME=C
END=