SIG_METHOD_NAME=C
META_DEPS=../../region/region_seam.cc/usr/bin/g++sys../point/point.h../shape/shape.hclimitscstdlibdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammpi.hparams/params.hsstreamstdexceptstringvectoruser../../region/region_seam.h
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAu0yqBUVcpP4gxLiXvP5wCwha3YNAtMdZOmbsqt3mDcfg
IMPLICIT_DEPS=
BUILD_SIGNATURE=1588417714,5064
ARCH=x86_64-linux-gnu-thread-multi
SORTED_DEPS=../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h../../region/region_seam.cc../../region/region_seam.h
INCLUDE_SFXS=
CWD=.
SIGNATURE=1588417714,5064
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN ../../region/region_seam.cc -o region_seam.o
IMPLICIT_TARGETS=region_seam.o
SIG_METHOD_IMPLICIT=1
END=