SORTED_DEPS=../../defines.h../../region/do_region_init.cc/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h../../region/region_seam.h../../spatial/spatial.h../../index/index.h../../parallel/hseg.h../../parallel/index.h../../parallel/pixel.h../../parallel/region_class.h../../parallel/region_object.h../../pixel/pixel.h../../region/region_class.h../../region/region_object.h../../rhseg/hseg.h
INCLUDE_SFXS=
SIG_METHOD_IMPLICIT=1
BUILD_SIGNATURE=1588417798,27584
SIG_METHOD_NAME=C
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../region/do_region_init.cc -o do_region_init.o
IMPLICIT_DEPS=
META_DEPS=../../region/do_region_init.cc/usr/bin/g++sys../defines.h../point/point.h../shape/shape.hclimitscstdlibcstringctimedefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparallel/region_class.hparallel/region_object.hparams/params.hpixel/pixel.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../region/region_class.hregion_object.hregion_seam.h
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQqsOA96AU0Rfw5k6BQTzPiQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAha3YNAtMdZOmbsqt3mDcfguqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQU0zUr4GDuuZM4IbkmJwifAp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgxlpppl+HgYGYCorfrhAbDgvm03ZpR0EzimwuTG4WA6Zg
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
IMPLICIT_TARGETS=do_region_init.o
ARCH=x86_64-linux-gnu-thread-multi
SIGNATURE=1588417798,27584
CWD=.
END=