META_DEPS=../../region/merge_regions.cc/usr/bin/g++sys../defines.hclimitscstdlibdefines.hfloat.hfstreamimage/image.hiostreammapmpi.hparallel/region_class.hparams/params.hsetsstreamstdexceptstringvectoruser../../region/region_class.h
ARCH=x86_64-linux-thread-multi
BUILD_SIGNATURE=1574278520,46160
CWD=.
INCLUDE_SFXS=
IMPLICIT_TARGETS=merge_regions.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../region/merge_regions.cc -o merge_regions.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../region/merge_regions.cc../../params/params.h../../parallel/region_class.h../../region/region_class.h
SIG_METHOD_NAME=C
SIG_METHOD_IMPLICIT=1
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608EYOYyaAvFhgDoolp1XSX/QiDuneRwt2XcpOLXZYEHjZAQkhYfQY2ZFHF5fjcjUcquQcHtwjdkjFzwbxwGCtTJaBg
SIGNATURE=1574278520,46160
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
END=