SIGNATURE=1574278526,85952
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/ggjuOGgPKZisdJk8h4wLvqAH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQ2GyqQujPwNLJwakQ0yjVmwU0zUr4GDuuZM4IbkmJwifAp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgzmdHk9xRrBHI0Qjmt+9msgxlpppl+HgYGYCorfrhAbDgvm03ZpR0EzimwuTG4WA6Zg
SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
IMPLICIT_TARGETS=region_object.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../region/region_object.cc -o region_object.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../params/params.h../../spatial/spatial.h../../parallel/hseg.h../../parallel/pixel.h../../parallel/region_class.h../../parallel/region_object.cc../../parallel/region_object.h../../pixel/pixel.h../../region/region_class.h../../region/region_object.cc../../region/region_object.h../../rhseg/hseg.h
CWD=.
INCLUDE_SFXS=
META_DEPS=../../region/region_object.cc/usr/bin/g++sys../defines.hclimitscmathcstdlibcstringdefines.hfloat.hfstreamimage/image.hiostreammapmpi.hparallel/hseg.hparallel/pixel.hparallel/region_class.hparallel/region_object.ccparallel/region_object.hparams/params.hpixel/pixel.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../region/region_class.hregion_object.h
ARCH=x86_64-linux-thread-multi
BUILD_SIGNATURE=1574278526,85952
END=