SIG_METHOD_NAME=C
IMPLICIT_DEPS=
CWD=.
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/wangp/wk/src/CommonV1.70/home/wangp/wk/src/RHSEG/rhsegV1.61/apps/gdal/2.2.3/include/usr/includeuserin CPATHin :sys
ARCH=x86_64-linux
META_DEPS=../../serialkey/serialkey.cc/usr/bin/g++sys../point/point.h../shape/shape.hcctypeclimitscpl_port.hcstdiocstdlibcstringctimedefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiomanipiostreammpi.hparams/params.hsstreamstdexceptstringvectoruser../../serialkey/serialkey.h
IMPLICIT_TARGETS=serialkey.o
BUILD_SIGNATURE=1534444973,24712
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/wangp/wk/src/CommonV1.70 -I/home/wangp/wk/src/RHSEG/rhsegV1.61 -I/apps/gdal/2.2.3/include -UTHREEDIM -DSERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../serialkey/serialkey.cc -o serialkey.o
INCLUDE_SFXS=
SORTED_DEPS=/apps/gdal/2.2.3/include/cpl_port.h../../defines.h/usr/bin/g++/apps/gdal/2.2.3/include/gdal_priv.h/apps/gdal/2.2.3/include/gdalwarper.h/gpfs/glad1/Panshi/src/CommonV1.70/image/image.h../../params/params.h../../serialkey/serialkey.cc../../serialkey/serialkey.h
DEP_SIGS=1516653975,44763z/QeDlmwxoI4L/bLCeMkSQ1523291714,7727441516653976,628201516653976,22263IaTZM6pejxn6nbNg6k5SVAiDuneRwt2XcpOLXZYEHjZAjqeqfw6gCk/TthqEq+9mPwbNRjCsEoBUaS/9NNn4qwvA
SIG_METHOD_IMPLICIT=1
SIGNATURE=1534444973,24712
END=