SIGNATURE=1588417781,2624
CWD=.
ARCH=x86_64-linux-gnu-thread-multi
IMPLICIT_DEPS=
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
META_DEPS=/usr/bin/g++hsegsizeobj.ccsys../defines.h../point/point.h../shape/shape.hclimitscmathcstdlibdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/region_class.hparallel/region_object.hregion/region_class.hregion/region_object.hresults/results.hsetsstreamstdexceptstringvectoruser./hsegsizeobj.hparams/initialParams.hparams/params.h
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009KVUD47u/6X2341IcP1pgAQqKA9jZlukDjgJD2UnJyLFACm5XOfDRYWcPtlBkU8K9Dwt2tyxL1aCgkHuZnq3JoOYgiDuneRwt2XcpOLXZYEHjZAbHzduVfmpQZiPcjKFstUvAQkhYfQY2ZFHF5fjcjUcquQU0zUr4GDuuZM4IbkmJwifAcHtwjdkjFzwbxwGCtTJaBgxlpppl+HgYGYCorfrhAbDg
IMPLICIT_TARGETS=hsegsizeobj.o
SORTED_DEPS=../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.hhsegsizeobj.cchsegsizeobj.h/home/pswang/src/CommonV1.70/image/image.hparams/initialParams.h../../params/params.h../../results/results.h../../parallel/region_class.h../../parallel/region_object.h../../region/region_class.h../../region/region_object.h
INCLUDE_SFXS=
SIG_METHOD_IMPLICIT=1
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_READ hsegsizeobj.cc -o hsegsizeobj.o
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417781,2624
END=