SIGNATURE=1588417836,52816
CWD=.
ARCH=x86_64-linux-gnu-thread-multi
IMPLICIT_DEPS=
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
META_DEPS=/usr/bin/g++main.ccsys../point/point.h../shape/shape.hclimitscstdlibcstringdefines.hexpParamsGUI.hfstreamgdal_priv.hgdalwarper.hgtkmm.hgui/fileObject.hgui/numberListObject.hgui/numberObject.himage/image.hiostreammpi.hparams/initialGUI.hparams/outputFileGUI.hparams/params.hparams/paramsGUI.hsstreamstdexceptstringvector
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQce1LpOPQ2i8GUOqymaDn9g1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9Dw0wanbfcnNkakvhmdf5v1qgjswVGE1VKQ7Dg86dFmu6GQ4qTCXXSbbllLkrb0vP3qYQzJOedzGRSkZBUFKXmYLZXAqj8Ivpinlk0EkcICCAFghgiDuneRwt2XcpOLXZYEHjZAFqUobXjx+i8JSyW4D0szcQ
IMPLICIT_TARGETS=main.o
SORTED_DEPS=../defines.h/home/pswang/src/CommonV1.70/gui/fileObject.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../params/initialGUI.hmain.cc/home/pswang/src/CommonV1.70/gui/numberListObject.h/home/pswang/src/CommonV1.70/gui/numberObject.h../params/outputFileGUI.h../params/params.h../params/paramsGUI.h
INCLUDE_SFXS=
SIG_METHOD_IMPLICIT=1
BUILD_SIGNATURE=1588417836,52816
SIG_METHOD_NAME=C
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_SETUP main.cc -o main.o
END=