IMPLICIT_DEPS=
IMPLICIT_TARGETS=sizeobj.o
DEP_SIGS=1585509601,177751585509601,22971z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9Dwt2tyxL1aCgkHuZnq3JoOYg1585509601,33749iDuneRwt2XcpOLXZYEHjZAbHzduVfmpQZiPcjKFstUvA2x0enP7zBiGHPT5Cbm+T5QQkhYfQY2ZFHF5fjcjUcquQU0zUr4GDuuZM4IbkmJwifAcHtwjdkjFzwbxwGCtTJaBgxlpppl+HgYGYCorfrhAbDg
META_DEPS=/usr/bin/g++sizeobj.ccsys../defines.h../point/point.h../shape/shape.hclimitscstdlibdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hogr_spatialref.hparallel/region_class.hparallel/region_object.hregion/region_class.hregion/region_object.hresults/results.hsetsstreamstdexceptstringvectoruser./cpl_conv.hcpl_string.hgdal_priv.hparams/initialParams.hparams/params.h
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
INCLUDE_SFXS=
SORTED_DEPS=/usr/include/gdal/cpl_conv.h/usr/include/gdal/cpl_string.h../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.hparams/initialParams.h/usr/include/gdal/ogr_spatialref.h../../params/params.h../../results/results.hsizeobj.cc../../parallel/region_class.h../../parallel/region_object.h../../region/region_class.h../../region/region_object.h
BUILD_SIGNATURE=1588417793,12000
SIG_METHOD_NAME=C
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_READ sizeobj.cc -o sizeobj.o
SIG_METHOD_IMPLICIT=1
SIGNATURE=1588417793,12000
CWD=.
ARCH=x86_64-linux-gnu-thread-multi
END=