BUILD_SIGNATURE=1574278526,4784
ARCH=x86_64-linux-thread-multi
META_DEPS=../../region/region_seam.cc/usr/bin/g++sysclimitscstdlibdefines.hfstreamimage/image.hiostreammpi.hparams/params.hsstreamstdexceptstringvectoruser../../region/region_seam.h
CWD=.
INCLUDE_SFXS=
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../region/region_seam.cc -o region_seam.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../params/params.h../../region/region_seam.cc../../region/region_seam.h
IMPLICIT_TARGETS=region_seam.o
SIG_METHOD_NAME=C
SIG_METHOD_IMPLICIT=1
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAu0yqBUVcpP4gxLiXvP5wCwha3YNAtMdZOmbsqt3mDcfg
IMPLICIT_DEPS=
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278526,4784
END=