INCLUDE_SFXS=
CWD=.
IMPLICIT_TARGETS=update_region_info.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../region/update_region_info.cc -o update_region_info.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../params/params.h../../spatial/spatial.h../../region/update_region_info.cc../../parallel/hseg.h../../parallel/pixel.h../../parallel/region_class.h../../parallel/region_object.h../../pixel/pixel.h../../region/region_class.h../../region/region_object.h../../rhseg/hseg.h
BUILD_SIGNATURE=1574278530,8552
ARCH=x86_64-linux-thread-multi
META_DEPS=../../region/update_region_info.cc/usr/bin/g++sys../defines.hclimitscstdlibcstringctimedefines.hfloat.hfstreamimage/image.hmapmpi.hparallel/hseg.hparallel/pixel.hparallel/region_class.hparallel/region_object.hparams/params.hpixel/pixel.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../region/region_class.hregion_object.h
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gvkmRP2tFBKSZwTDTyb/bwQgjuOGgPKZisdJk8h4wLvqAH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQU0zUr4GDuuZM4IbkmJwifAp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgxlpppl+HgYGYCorfrhAbDgvm03ZpR0EzimwuTG4WA6Zg
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278530,8552
SIG_METHOD_NAME=C
SIG_METHOD_IMPLICIT=1
END=