CWD=.
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN check_buf_size.cc -o check_buf_size.o
SIGNATURE=1588417686,7168
SIG_METHOD_IMPLICIT=1
IMPLICIT_TARGETS=check_buf_size.o
META_DEPS=/usr/bin/g++check_buf_size.ccsys../point/point.h../shape/shape.hclimitscstdlibdefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparams/params.hsetsstreamstdexceptstringvectoruser./hseg.h
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
BUILD_SIGNATURE=1588417686,7168
IMPLICIT_DEPS=
DEP_SIGS=d80VbDqhqANtmyx4LWWajgz/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAgjuOGgPKZisdJk8h4wLvqAvm03ZpR0EzimwuTG4WA6Zg
INCLUDE_SFXS=
SORTED_DEPS=check_buf_size.cc../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../params/params.h../parallel/hseg.hhseg.h
ARCH=x86_64-linux-gnu-thread-multi
END=