SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278510,5880
IMPLICIT_DEPS=
DEP_SIGS=d80VbDqhqANtmyx4LWWajgz/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAgjuOGgPKZisdJk8h4wLvqAvm03ZpR0EzimwuTG4WA6Zg
BUILD_SIGNATURE=1574278510,5880
ARCH=x86_64-linux-thread-multi
META_DEPS=../rhseg/check_buf_size.cc/usr/bin/g++sysclimitscstdlibdefines.hfstreamimage/image.hmapmpi.hparallel/hseg.hparams/params.hsetsstreamstdexceptstringvectoruser../rhseg/hseg.h
IMPLICIT_TARGETS=check_buf_size.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/check_buf_size.cc -o check_buf_size.o
SORTED_DEPS=../rhseg/check_buf_size.cc../defines.h/usr/bin/g++../params/params.h../parallel/hseg.h../rhseg/hseg.h
CWD=.
INCLUDE_SFXS=
END=