BUILD_SIGNATURE=1574278515,20792
ARCH=x86_64-linux-thread-multi
META_DEPS=../rhseg/heap.cc/usr/bin/g++sys../defines.halgorithmclimitscstdlibdefines.hfloat.hfstreamimage/image.hmapmpi.hparallel/hseg.hparallel/region_class.hparams/params.hregion/region_class.hsetsstreamstdexceptstringvectoruser../rhseg/hseg.h
SORTED_DEPS=../defines.h/usr/bin/g++../rhseg/heap.cc../params/params.h../parallel/hseg.h../parallel/region_class.h../region/region_class.h../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/heap.cc -o heap.o
IMPLICIT_TARGETS=heap.o
CWD=.
INCLUDE_SFXS=
SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278515,20792
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608pyS6WLhq4TiLdIkHj4E/egiDuneRwt2XcpOLXZYEHjZAgjuOGgPKZisdJk8h4wLvqAQkhYfQY2ZFHF5fjcjUcquQcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
END=