# Makefile for the GUI object classes

%.o: $(COMMON_DIR)/gui/%.cc
    $(CPP) -c $(CPPFLAGS) $(DEFINES) $(input) -o $(output)

OBJECTS := fileObject.o numberListObject.o numberObject.o

all: $(OBJECTS)

