BUILD_SIGNATURE=1574278512,12200
ARCH=x86_64-linux-thread-multi
META_DEPS=../../pixel/do_region_relabel.cc/usr/bin/g++sysclimitscstdlibcstringctimedefines.hfstreamimage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparams/params.hpixel/pixel.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../pixel/pixel.h
SORTED_DEPS=../../defines.h../../pixel/do_region_relabel.cc/usr/bin/g++../../params/params.h../../spatial/spatial.h../../index/index.h../../parallel/hseg.h../../parallel/index.h../../parallel/pixel.h../../pixel/pixel.h../../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../pixel/do_region_relabel.cc -o do_region_relabel.o
IMPLICIT_TARGETS=do_region_relabel.o
CWD=.
INCLUDE_SFXS=
SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIGNATURE=1574278512,12200
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQm6FtHhtMizhe4n5CpqqcWw1566927917,1226608iDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7Cgp8ynGaUtUItYTP9WYpFtZAvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
END=