INCLUDE_SFXS=
CWD=.
IMPLICIT_TARGETS=pixel.o
SORTED_DEPS=../../defines.h/usr/bin/g++../../params/params.h../../spatial/spatial.h../../parallel/hseg.h../../parallel/pixel.cc../../parallel/pixel.h../../parallel/region_class.h../../pixel/pixel.cc../../pixel/pixel.h../../region/region_class.h../../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/rhsegV1.61 -DTHREEDIM -USERIALKEY -UGTKMM -UGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../../pixel/pixel.cc -o pixel.o
META_DEPS=../../pixel/pixel.cc/usr/bin/g++sys../defines.hclimitscmathcstdlibcstringdefines.hfloat.hfstreamimage/image.hiostreammapmpi.hparallel/hseg.hparallel/pixel.ccparallel/pixel.hparallel/region_class.hparams/params.hregion/region_class.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../pixel/pixel.h
ARCH=x86_64-linux-thread-multi
BUILD_SIGNATURE=1574278523,70040
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1566927917,1226608iDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/ggjuOGgPKZisdJk8h4wLvqA6VajAoeghONw5rOdgV8G3AH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQhg6bnSY+yLFAw5WAdaBzCQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
SIGNATURE=1574278523,70040
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/rhsegV1.61/usr/includeuserin CPATHin :sys
SIG_METHOD_NAME=C
SIG_METHOD_IMPLICIT=1
END=