SIGNATURE=1588417709,72040
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN ../../pixel/pixel.cc -o pixel.o
IMPLICIT_TARGETS=pixel.o
SIG_METHOD_IMPLICIT=1
CWD=.
IMPLICIT_DEPS=
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/ggjuOGgPKZisdJk8h4wLvqA6VajAoeghONw5rOdgV8G3AH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQhg6bnSY+yLFAw5WAdaBzCQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
BUILD_SIGNATURE=1588417709,72040
ARCH=x86_64-linux-gnu-thread-multi
INCLUDE_SFXS=
SORTED_DEPS=../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h../../spatial/spatial.h../../parallel/hseg.h../../parallel/pixel.cc../../parallel/pixel.h../../parallel/region_class.h../../pixel/pixel.cc../../pixel/pixel.h../../region/region_class.h../hseg.h
META_DEPS=../../pixel/pixel.cc/usr/bin/g++sys../defines.h../point/point.h../shape/shape.hclimitscmathcstdlibcstringdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparallel/pixel.ccparallel/pixel.hparallel/region_class.hparams/params.hregion/region_class.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../pixel/pixel.h
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
END=