SIG_METHOD_IMPLICIT=1
IMPLICIT_TARGETS=artifact_elimination.o
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN artifact_elimination.cc -o artifact_elimination.o
SIGNATURE=1588417684,12424
CWD=.
SORTED_DEPS=artifact_elimination.cc../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../params/params.h../region/region_seam.h../index/index.h../parallel/hseg.h../parallel/index.h../parallel/pixel.h../parallel/region_class.h../pixel/pixel.h../region/region_class.hhseg.h
INCLUDE_SFXS=
ARCH=x86_64-linux-gnu-thread-multi
BUILD_SIGNATURE=1588417684,12424
DEP_SIGS=sZ/ysT+KoaIAfwq++J6gGAz/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAha3YNAtMdZOmbsqt3mDcfgWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
SIG_METHOD_NAME=C
META_DEPS=/usr/bin/g++artifact_elimination.ccsys../defines.h../point/point.h../shape/shape.hclimitscstdlibdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparallel/region_class.hparams/params.hpixel/pixel.hregion/region_class.hregion/region_seam.hrhseg/hseg.hsetsstreamstdexceptstringvectoruser./hseg.h
END=