CWD=.
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DCONSOLIDATED -DRHSEG_RUN ../../index/index.cc -o index.o
SIGNATURE=1588417700,9056
SIG_METHOD_IMPLICIT=1
IMPLICIT_TARGETS=index.o
META_DEPS=../../index/index.cc/usr/bin/g++sys../defines.h../point/point.h../shape/shape.hclimitscstdlibcstringdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparallel/index.ccparallel/index.hparallel/pixel.hparallel/region_class.hparams/params.hpixel/pixel.hregion/region_class.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../../index/index.h
SIG_METHOD_NAME=C
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
BUILD_SIGNATURE=1588417700,9056
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/g0KEJaT4HrHhcTew/tP9OvwWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqA/4wawWsKlfS4kSaw21t50gubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
INCLUDE_SFXS=
SORTED_DEPS=../../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../../params/params.h../../spatial/spatial.h../../index/index.cc../../index/index.h../../parallel/hseg.h../../parallel/index.cc../../parallel/index.h../../parallel/pixel.h../../parallel/region_class.h../../pixel/pixel.h../../region/region_class.h../hseg.h
ARCH=x86_64-linux-gnu-thread-multi
END=