SIGNATURE=1588417801,31384
CWD=.
ARCH=x86_64-linux-gnu-thread-multi
IMPLICIT_DEPS=
META_DEPS=../rhseg/first_merge_reg_grow.cc/usr/bin/g++sys../defines.h../point/point.h../shape/shape.halgorithmclimitscstdlibdefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparallel/pixel.hparallel/region_class.hparams/params.hpixel/pixel.hregion/region_class.hrhseg/hseg.hsetsstreamstdexceptstringtime.hvectoruser../rhseg/hseg.h
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQwkc4gQYhmSnCu/nECBFqig1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZA1586892364,10276gjuOGgPKZisdJk8h4wLvqAH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_TARGETS=first_merge_reg_grow.o
SORTED_DEPS=../defines.h../rhseg/first_merge_reg_grow.cc/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../params/params.h/usr/include/time.h../parallel/hseg.h../parallel/pixel.h../parallel/region_class.h../pixel/pixel.h../region/region_class.h../rhseg/hseg.h
INCLUDE_SFXS=
SIG_METHOD_IMPLICIT=1
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417801,31384
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/first_merge_reg_grow.cc -o first_merge_reg_grow.o
END=