ARCH=x86_64-linux-gnu-thread-multi
SIGNATURE=1588417806,92560
CWD=.
INCLUDE_SFXS=
SORTED_DEPS=../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h../rhseg/hseg.cc/home/pswang/src/CommonV1.70/image/image.h../params/params.h/usr/include/pthread.h../results/results.h../spatial/spatial.h../parallel/hseg.h../parallel/pixel.h../parallel/region_class.h../parallel/region_object.h../pixel/pixel.h../region/region_class.h../region/region_object.h../rhseg/hseg.h
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/hseg.cc -o hseg.o
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417806,92560
SIG_METHOD_IMPLICIT=1
IMPLICIT_DEPS=
IMPLICIT_TARGETS=hseg.o
META_DEPS=../rhseg/hseg.cc/usr/bin/g++sys../defines.h../point/point.h../shape/shape.halgorithmclimitscmathcstdlibcstringctimedefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparallel/pixel.hparallel/region_class.hparallel/region_object.hparams/params.hpixel/pixel.hpthread.hregion/region_class.hregion/region_object.hresults/results.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../rhseg/hseg.h
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009NhI2uxOIBazhQBx6toy/jwCm5XOfDRYWcPtlBkU8K9DwiDuneRwt2XcpOLXZYEHjZA1586892364,41701bHzduVfmpQZiPcjKFstUvAuqVJLOXFsS3kiHM31G/1/ggjuOGgPKZisdJk8h4wLvqAH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQU0zUr4GDuuZM4IbkmJwifAp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgxlpppl+HgYGYCorfrhAbDgvm03ZpR0EzimwuTG4WA6Zg
END=