SIGNATURE=1588417813,56288
CWD=.
ARCH=x86_64-linux-gnu-thread-multi
IMPLICIT_DEPS=
IMPLICIT_TARGETS=lrhseg.o
META_DEPS=../rhseg/lrhseg.cc/usr/bin/g++sys../defines.h../point/point.h../shape/shape.halgorithmclimitscstdlibcstringctimedefines.hfloat.hfstreamgdal_priv.hgdalwarper.himage/image.hindex/index.hiostreammapmpi.hparallel/hseg.hparallel/index.hparallel/pixel.hparallel/region_class.hparams/params.hpixel/pixel.hregion/region_class.hrhseg/hseg.hsetspatial/spatial.hsstreamstdexceptstringvectoruser../rhseg/hseg.h
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9Dw9imYklOwtG68GzkJvaSsvAiDuneRwt2XcpOLXZYEHjZAuqVJLOXFsS3kiHM31G/1/gWWYp2WWUtnnjHF4AVUbJZwgjuOGgPKZisdJk8h4wLvqAubc2HcU4CSfKM0bkzo8ExwH6t/l0ZBFX4I/UBMIG/7CgQkhYfQY2ZFHF5fjcjUcquQp8ynGaUtUItYTP9WYpFtZAcHtwjdkjFzwbxwGCtTJaBgvm03ZpR0EzimwuTG4WA6Zg
INCLUDE_SFXS=
SORTED_DEPS=../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.h../rhseg/lrhseg.cc../params/params.h../spatial/spatial.h../index/index.h../parallel/hseg.h../parallel/index.h../parallel/pixel.h../parallel/region_class.h../pixel/pixel.h../region/region_class.h../rhseg/hseg.h
BUILD_SIGNATURE=1588417813,56288
SIG_METHOD_NAME=C
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN ../rhseg/lrhseg.cc -o lrhseg.o
SIG_METHOD_IMPLICIT=1
END=