IMPLICIT_TARGETS=main.o
META_DEPS=/usr/bin/g++main.ccsys../point/point.h../shape/shape.hclimitscstdlibcstringctimedefines.hfstreamgdal_priv.hgdalwarper.himage/image.hiostreammapmpi.hparallel/hseg.hparams/params.hrhseg/hseg.hserialkey/serialkey.hsetsstreamstdexceptstringvector
INCLUDE_PATHS=sysin CPLUS_INCLUDE_PATH/home/pswang/src/CommonV1.70/home/pswang/src/rhsegV1.61/usr/include/gdal/usr/includeuserin CPATHin :sys
DEP_SIGS=z/QeDlmwxoI4L/bLCeMkSQ1586428689,11582881585509601,723681585509601,24009Cm5XOfDRYWcPtlBkU8K9Dw50N+JLnqhrvr2Srj6N6NyAiDuneRwt2XcpOLXZYEHjZAbNRjCsEoBUaS/9NNn4qwvAgjuOGgPKZisdJk8h4wLvqAvm03ZpR0EzimwuTG4WA6Zg
IMPLICIT_DEPS=
SIG_METHOD_NAME=C
BUILD_SIGNATURE=1588417813,42568
COMMAND=g++ -c -Wall -O3 -ffloat-store -Wno-unused-result -I/home/pswang/src/CommonV1.70 -I/home/pswang/src/rhsegV1.61 -I/usr/include/gdal -UTHREEDIM -USERIALKEY -UGTKMM -DGDAL -USHAPEFILE -UPARALLEL -UWINDOWS -DRHSEG_RUN main.cc -o main.o
SIG_METHOD_IMPLICIT=1
INCLUDE_SFXS=
SORTED_DEPS=../defines.h/usr/bin/g++/usr/include/gdal/gdal_priv.h/usr/include/gdal/gdalwarper.h/home/pswang/src/CommonV1.70/image/image.hmain.cc../params/params.h../serialkey/serialkey.h../parallel/hseg.h../rhseg/hseg.h
CWD=.
SIGNATURE=1588417813,42568
ARCH=x86_64-linux-gnu-thread-multi
END=